project:
  type: website

website:
  title: "California Crime Dashboard"
  navbar:
    left:
      - text: Overview
        href: index.qmd
      - text: Cities
        menu:
          - text: San Diego
            href: sd.qmd
          - text: Los Angeles
            href: la.qmd
          - text: San Francisco
            href: sf.qm
      - text: Prediction
        menu:
        - text: Forecast - Prophet
          href: forecast_prophet.qmd
        - text: Linear Regression
          href: linear_regression.qmd
      - text: About
        menu:
          - href: data_schema.qmd
            text: Data Schema
    right:
      - icon: github
        href: https://github.com/rsm-fluan/california-crime-dashboard

  page-footer:
    left: "Â© 2025 California Crime Dashboard"
    right:
      - text: "Data Sources"
        href: data_schema.qmd
      - text: "GitHub"
        href: https://github.com/rsm-fluan/california-crime-dashboard

format:
  html:
    theme: zephyr
    toc: true
    code-fold: true
    code-tools: false
    code-link: false
