name: rsm-msba-k8s-latest

services:
  rsm-msba:
    image: vnijs/rsm-msba-k8s:latest
    container_name: rsm-msba-k8s-latest
    hostname: rsm-msba-k8s
    environment:
      TZ: America/Los_Angeles
      USER: jovyan
      HOME: /home/jovyan
      SHELL: /bin/zsh
      ZDOTDIR: /home/jovyan/.rsm-msba/zsh
      RSMBASE: /home/jovyan/.rsm-msba
    volumes:
      - ${HOME}:/home/jovyan
      - pg_data:/var/lib/postgresql/16/main
    networks:
      - rsm-docker

networks:
  rsm-docker:
    name: rsm-docker

volumes:
  pg_data:
    name: pg_data
